[workspace]
resolver = "2"

members = [
  "app",
  "chain",
  "config",
  "crypto",
  "encoding",
  "node",
  "plz"
]

[workspace.dependencies]
async-trait                 = { version = "0.1",  default-features = false }
bcs                         = { version = "0.1",  default-features = false }
bech32                      = { version = "0.9",  default-features = false }
bytes                       = { version = "1.4",  default-features = false }
console-subscriber          = { version = "0.1",  default-features = false }
dialoguer                   = { version = "0.10", default-features = false }
directories                 = { version = "4.0",  default-features = false }
ed25519-consensus           = { version = "2.1",  default-features = false }
eyre                        = { version = "0.6",  default-features = false }
futures                     = { version = "0.3",  default-features = false }
hex                         = { version = "0.4",  default-features = false }
lexopt                      = { version = "0.3",  default-features = false }
metrics-exporter-prometheus = { version = "0.11", default-features = false }
metrics-tracing-context     = { version = "0.13", default-features = false }
metrics-util                = { version = "0.14", default-features = false }
num-traits                  = { version = "0.2",  default-features = false }
once_cell                   = { version = "1.18", default-features = false }
penumbra-storage            = { git = "https://github.com/penumbra-zone/penumbra", branch = "main", default-features = false }
pretty_assertions           = { version = "1.4",  default-features = false }
radicle-cli-test            = { version = "0.1",  default-features = false }
rand                        = { version = "0.8",  default-features = false }
serde                       = { version = "1.0",  default-features = false }
sha2                        = { version = "0.10", default-features = false }
tempfile                    = { version = "3.7",  default-features = false }
tendermint                  = { version = "0.32", default-features = false }
tendermint-rpc              = { version = "0.29", default-features = false }
thiserror                   = { version = "1.0",  default-features = false }
tokio                       = { version = "1.28", default-features = false }
tokio-util                  = { version = "0.7",  default-features = false }
tower-abci                  = { version = "0.5",  default-features = false }
tower-service               = { version = "0.3",  default-features = false }
tracing                     = { version = "0.1",  default-features = false }
tracing-subscriber          = { version = "0.3",  default-features = false }

[workspace.package]
authors       = ["Pulzaar Team <core@pulzaar.zone>"]
edition       = "2021"
license       = "MIT or Apache-2.0"
homepage      = "https://pulzaar.zone"
repository    = "https://github.com/pulzaar-zone/pulzaar"
rust-version  = "1.67"
publish       = false

[profile.release]
lto       = true
opt-level = 3
panic     = "unwind"
