[package]
name      = "guest-celestia"
version   = "0.1.0"
edition   = "2021"
resolver  = "2"

[workspace]

[dependencies]
hub-stf = { path = "../../../stf" }

sov-celestia-adapter      = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }
sov-modules-api           = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }
sov-modules-stf-blueprint = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }
sov-rollup-interface      = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }
sov-risc0-adapter         = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }
sov-state                 = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "c5ef0fe" }

anyhow              = { version = "1.0.68" }
risc0-zkvm          = { version = "0.19", default-features = false, features = ["std"] }
risc0-zkvm-platform = { version = "0.19" }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }

# Uncomment to apply the v0.19 build script downlaod issue hotfix.
risc0-circuit-recursion = { git = "https://github.com/neysofu/risc0-hotfixes", rev = "v0.19.2-hotfix" }
risc0-circuit-rv32im    = { git = "https://github.com/neysofu/risc0-hotfixes", rev = "v0.19.2-hotfix" }
risc0-zkvm              = { git = "https://github.com/neysofu/risc0-hotfixes", rev = "v0.19.2-hotfix" }
risc0-zkvm-platform     = { git = "https://github.com/neysofu/risc0-hotfixes", rev = "v0.19.2-hotfix" }


[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
