[package]
name                  = "pulzaar-app"
version               = "0.1.0"
authors.workspace     = true
edition.workspace     = true
homepage.workspace    = true
repository.workspace  = true
publish.workspace     = true

[dependencies]
pulzaar-chain     = { path = "../chain" }

async-trait       = { workspace = true }
eyre              = { workspace = true }
penumbra-storage  = { workspace = true }
tendermint        = { workspace = true }
