[package]
name                    = "pulzaar-chain"
version                 = "0.1.0"
authors.workspace       = true
edition.workspace       = true
repository.workspace    = true
homepage.workspace      = true
license.workspace       = true
rust-version.workspace  = true
publish.workspace       = true

[dependencies]
pulzaar-encoding = { path = "../encoding" }

async-trait       = { workspace = true }
cosmrs            = { workspace = true }
ed25519-consensus = { workspace = true, features = [ "serde", "std" ] }
eyre              = { workspace = true }
hex               = { workspace = true, features = [ "alloc" ] }
penumbra-storage  = { workspace = true }
sha2              = { workspace = true }
serde             = { workspace = true, features = [ "derive" ] }
tendermint        = { workspace = true }
