[package]
name    = "pulzaar-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait       = { version = "0.1", default-features = false }
eyre              = { version = "0.6",  default-features = false }
hex               = { version = "0.4",  default-features = false, features = [ "alloc" ] }
penumbra-storage  = { git = "https://github.com/penumbra-zone/penumbra", branch = "main" }
sha2              = { version = "0.10", default-features = false }
