name: Buf
on:
  push:
    branches:
      - main

jobs:
  publish-proto:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Publish Protobuf definitions
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1

      - name: Publish definitions
        uses: bufbuild/buf-push-action@v1
        with:
          input: "proto/proto"
          buf_token: ${{ secrets.BUF_TOKEN }}
