name: CI
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Lint Markdown
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm install

      - uses: xt0rted/markdownlint-problem-matcher@v2
      - run: npm run markdownlint
