name: Docs
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  deploy-docs:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-22.04-16core]
        toolchain: [stable]

    name: Deploy docs
    runs-on: ${{ matrix.os }}
    outputs:
      spec-url: ${{ steps.spec-cloudflare-deploy.outputs.alias }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: cargo, clippy, rustfmt
          override: true

      - name: Cache dependencies & tools
        uses: Swatinem/rust-cache@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          key: ${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Setup mdBook
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: cargo install mdbook mdbook-katex mdbook-linkcheck mdbook-mermaid mdbook-toc

      - name: Build Spec
        run: |
          mdbook test docs/spec
          mdbook build docs/spec

      - id: spec-cloudflare-deploy
        name: Publish Spec to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: filament-spec
          directory: docs/spec/book/html/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  summary:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Summary
    needs: [deploy-docs]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add comment with deployed preview links
        uses: mshick/add-pr-comment@v2
        with:
          message-id: deploy-summary
          message: |
            ### Previews
            | **Site**    | **URL**                                                                                            | 
            |-------------|----------------------------------------------------------------------------------------------------|
            | **Spec**    | [${{ needs.deploy-docs.outputs.spec-url }}](${{ needs.deploy-docs.outputs.spec-url }})             |
